### ISSUE TITLE
南邮黄页

### ISSUE THREAD

**Issue by Wonz5130** [seuite/awesome-seu#10]
**项目名**
NJUPT-Yellow-Page 南邮黄页

**项目内容**
个人收集整理了南京邮电大学的资源，希望与友校 `SEU` 进行 `联动`，添加友情链接。

**项目链接**
https://github.com/Wonz5130/NJUPT-Yellow-Page

**项目作者**
[Wonz](https://github.com/Wonz5130)

**Comment by c4yg70** [comment]
已添加，欢迎常过来玩www
